export default function Head() {
	return (
		<>
			<title>Calendar Event Todo</title>
			<meta content='width=device-width, initial-scale=1' name='viewport' />
			<meta name='description' content='Generated by create next app' />
			<link rel='icon' href='/favicon.ico' />

			<link
				rel='stylesheet'
				href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css'
				precedence='default'
			/>
			<link
				href='https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css'
				rel='stylesheet'
				integrity='sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65'
				crossorigin='anonymous'
				precedence='default'
			/>
		</>
	);
}
